FROM python:3.9-slim-buster

# Install necessary packages and libraries
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/exoscale/cli/releases/download/v1.66.0/exoscale-cli_1.66.0_linux_amd64.deb && \
    dpkg -i /exoscale-cli_1.66.0_linux_amd64.deb

# Install the ASReview package and gensim sentence-transformers
RUN pip install asreview 

# Create a folder for the Exoscale CLI
RUN mkdir -p /app/exoscale

# Create exoscale.toml file
ENV EXOSCALE_CONFIG=/app/exoscale/exoscale.toml

# Set up the working directory and copy the script
WORKDIR /app

# Copy the simulation script into the container
COPY run_simulation.sh .

# Set the entrypoint and default command
ENTRYPOINT ["./run_simulation.sh"]
CMD []

